#! /bin/bash
num=$((RANDOM%900+100))
num=$((RANDOM%900+100))
num=$((RANDOM%900+100))
s=0
rev=" "
temp=$num
while [ $num -gt 0 ]
do
s=$(( $num % 10 ))
num=$(( $num / 10 ))
rev=$( echo ${rev}${s} ) 
done
if [ $temp -eq $rev ]
then
echo "$temp palindrome"
else
echo " $temp not palindrome"
fi
